name: CD

on: delete

env:
  CI: true
jobs:
  unpublish-npm:
    runs-on: ubuntu-18.04
    if: github.event.ref_type == 'branch'
    steps:
    - name: Prepare for unpublication from npm
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Determine npm tag
      # Remove non-alphanumeric characters
      # See https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      run: echo "TAG_SLUG=$(echo "${{ github.event.ref }}" | tr -cd '[:alnum:]-')" >> $GITHUB_ENV
    - name: Remove npm tag for the deleted branch
      run: |
        # Unfortunately GitHub Actions does not currently let us do something like
        #     if: secrets.NPM_TOKEN != ''
        # so simply skip the command if the env var is not set:
        if [ -n $NODE_AUTH_TOKEN ]; then npm dist-tag rm @inrupt/solid-client $TAG_SLUG; fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: echo "Package tag [$TAG_SLUG] unpublished."
