name: CD â€” unpublish

on: delete

env:
  CI: true
jobs:
  unpublish-npm:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Prepare for unpublication from npm
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Determine npm tag
        # Remove non-alphanumeric characters
        # See https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: echo "TAG_SLUG=$(echo "${{ github.event.ref }}" | tr -cd '[:alnum:]-')" >> $GITHUB_ENV
      - name: Remove npm tag for the deleted branch
        run: |
          export EXISTING_TAGS=$(npm dist-tag ls @inrupt/solid-client | grep --count $TAG_SLUG)
          # Unfortunately GitHub Actions does not currently let us do something like
          #     if: secrets.NPM_TOKEN != ''
          # so simply skip the command if the env var is not set
          # or if the package was not published under this tag
          # (e.g. for Dependabot Pull Requests):
          if [ -n $NODE_AUTH_TOKEN ] && [ $EXISTING_TAGS -eq 1 ]; then npm dist-tag rm @inrupt/solid-client $TAG_SLUG; fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: echo "Package tag [$TAG_SLUG] unpublished."
